# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "petsta"
description = "A minimalist theme for my blog"
tags = ["tags", "categories"]
min_version = 0.17

[author]
  name = "Peter Stace"
  homepage = "peterstace.io"
